-- Migration 002: Seed ~50 most-trafficked wildlife species
-- Sources: CITES Appendices, IUCN Red List, UNODC/TRAFFIC seizure reports

INSERT INTO species_ref (scientific_name, common_name, common_names_local, cites_appendix, iucn_status, population_trend, range_countries, trade_suspension_active, trade_suspension_countries, typical_products, black_market_price_range) VALUES

-- ── ELEPHANTS (2) ──────────────────────────────────────────────────────────
('Loxodonta africana', 'African Elephant',
 '{"th": "ช้างแอฟริกา", "vi": "Voi châu Phi", "zh": "非洲象", "id": "Gajah Afrika"}',
 'I', 'EN', 'decreasing',
 ARRAY['KE','TZ','ZA','BW','ZW','MZ','ZM','MW','CD','CM','GA','CG','CF','TD','NG','GH','CI','SL','LR','GN','SN','ML','BF','BJ','TG','ET','SS','UG','RW'],
 false, '{}',
 ARRAY['ivory_raw','ivory_carved','ivory_jewelry','ivory_chopsticks','ivory_figurines'],
 '{"ivory_per_kg_usd": {"low": 500, "high": 3000}}'),

('Elephas maximus', 'Asian Elephant',
 '{"th": "ช้างเอเชีย", "vi": "Voi châu Á", "zh": "亚洲象", "id": "Gajah Asia"}',
 'I', 'EN', 'decreasing',
 ARRAY['IN','LK','THA','MMR','LAO','KHM','VNM','CHN','MYS','IDN','BGD','NPL','BTN'],
 false, '{}',
 ARRAY['ivory_raw','ivory_carved','skin','live_juvenile'],
 '{"ivory_per_kg_usd": {"low": 600, "high": 3500}}'),

-- ── PANGOLINS (4) ──────────────────────────────────────────────────────────
('Manis javanica', 'Sunda Pangolin',
 '{"th": "ตัวนิ่มซุนดา", "vi": "Tê tê Java", "zh": "马来穿山甲", "id": "Trenggiling Sunda"}',
 'I', 'CR', 'decreasing',
 ARRAY['IDN','MYS','THA','SGP','VNM','KHM','LAO','MMR','CHN'],
 false, '{}',
 ARRAY['scales','meat','whole_frozen','fetus','blood'],
 '{"scales_per_kg_usd": {"low": 600, "high": 3000}, "live_per_animal_usd": {"low": 1000, "high": 5000}}'),

('Manis pentadactyla', 'Chinese Pangolin',
 '{"th": "ตัวนิ่มจีน", "vi": "Tê tê Trung Quốc", "zh": "中华穿山甲", "id": "Trenggiling Cina"}',
 'I', 'CR', 'decreasing',
 ARRAY['CHN','VNM','LAO','THA','MMR','IND','NPL','BGD','TWN'],
 false, '{}',
 ARRAY['scales','meat','whole_frozen','traditional_medicine'],
 '{"scales_per_kg_usd": {"low": 800, "high": 3000}}'),

('Manis temminckii', 'Ground Pangolin',
 '{"zh": "南非穿山甲", "vi": "Tê tê đất"}',
 'I', 'VU', 'decreasing',
 ARRAY['KE','TZ','ZA','ZW','BW','ZM','MW','MOZ','NAM','AGO','UGA','ETH','SSD'],
 false, '{}',
 ARRAY['scales','meat','whole_frozen'],
 '{"scales_per_kg_usd": {"low": 400, "high": 2500}}'),

('Manis tricuspis', 'African White-bellied Pangolin',
 '{"zh": "白腹穿山甲", "vi": "Tê tê bụng trắng"}',
 'I', 'VU', 'decreasing',
 ARRAY['NGA','CMR','CAF','COD','GHA','CIV','GAB','COG','GNQ','SLE','LBR','GUI'],
 false, '{}',
 ARRAY['scales','meat','whole_frozen'],
 '{"scales_per_kg_usd": {"low": 350, "high": 2200}}'),

-- ── RHINOS (2) ─────────────────────────────────────────────────────────────
('Ceratotherium simum', 'White Rhinoceros',
 '{"th": "แรดขาว", "vi": "Tê giác trắng", "zh": "白犀牛", "id": "Badak Putih"}',
 'I', 'NT', 'increasing',
 ARRAY['ZAF','NAM','ZWE','KEN','UGA','ZMB','BWA','MOZ'],
 false, '{}',
 ARRAY['horn_raw','horn_powder','horn_carved','horn_jewelry'],
 '{"horn_per_kg_usd": {"low": 20000, "high": 65000}}'),

('Dicerorhinus sumatrensis', 'Sumatran Rhinoceros',
 '{"th": "แรดสุมาตรา", "vi": "Tê giác Sumatra", "zh": "苏门答腊犀牛", "id": "Badak Sumatera"}',
 'I', 'CR', 'decreasing',
 ARRAY['IDN','MYS'],
 false, '{}',
 ARRAY['horn_raw','horn_powder','skin','bone'],
 '{"horn_per_kg_usd": {"low": 30000, "high": 80000}}'),

-- ── TIGERS (1) ─────────────────────────────────────────────────────────────
('Panthera tigris', 'Tiger',
 '{"th": "เสือโคร่ง", "vi": "Hổ", "zh": "老虎", "id": "Harimau"}',
 'I', 'EN', 'decreasing',
 ARRAY['IND','RUS','CHN','THA','MMR','VNM','LAO','KHM','MYS','IDN','BGD','NPL','BTN'],
 false, '{}',
 ARRAY['bone','skin','teeth','claws','wine_bone','meat','live'],
 '{"skin_usd": {"low": 10000, "high": 50000}, "bone_per_kg_usd": {"low": 150, "high": 700}}'),

-- ── TURTLES / TORTOISES (6) ────────────────────────────────────────────────
('Geochelone elegans', 'Indian Star Tortoise',
 '{"th": "เต่าดาวอินเดีย", "vi": "Rùa sao Ấn Độ", "zh": "印度星龟", "id": "Kura-kura Bintang India"}',
 'I', 'VU', 'decreasing',
 ARRAY['IND','PAK','LKA'],
 false, '{}',
 ARRAY['live_pet','shell_ornament'],
 '{"live_per_animal_usd": {"low": 300, "high": 3000}}'),

('Indotestudo forstenii', 'Sulawesi Tortoise',
 '{"id": "Kura-kura Sulawesi", "zh": "苏拉威西陆龟"}',
 'II', 'EN', 'decreasing',
 ARRAY['IDN'],
 false, '{}',
 ARRAY['live_pet','meat'],
 '{"live_per_animal_usd": {"low": 200, "high": 1500}}'),

('Cuora mouhotii', 'Keeled Box Turtle',
 '{"vi": "Rùa hộp lưng gờ", "zh": "锯缘摄龟", "th": "เต่ากล่อง"}',
 'II', 'EN', 'decreasing',
 ARRAY['VNM','CHN','LAO','THA','MMR','IND'],
 false, '{}',
 ARRAY['live_pet','traditional_medicine','meat'],
 '{"live_per_animal_usd": {"low": 100, "high": 800}}'),

('Batagur baska', 'Northern River Terrapin',
 '{"th": "เต่าแม่น้ำ", "vi": "Rùa sông", "zh": "河龟"}',
 'I', 'CR', 'decreasing',
 ARRAY['IND','BGD','MMR','THA','MYS','IDN'],
 false, '{}',
 ARRAY['meat','eggs','live_pet','shell'],
 '{"live_per_animal_usd": {"low": 200, "high": 2000}}'),

('Chelonia mydas', 'Green Sea Turtle',
 '{"th": "เต่าทะเลสีเขียว", "vi": "Rùa xanh", "zh": "绿海龟", "id": "Penyu Hijau"}',
 'I', 'EN', 'decreasing',
 ARRAY['IDN','MYS','AUS','MEX','CRI','PAN','USA','BRA','MOZ','KEN','TZA','IND'],
 false, '{}',
 ARRAY['eggs','meat','shell_jewelry','oil','live'],
 '{"egg_per_100_usd": {"low": 30, "high": 200}}'),

('Geochelone sulcata', 'African Spurred Tortoise',
 '{"zh": "苏卡达陆龟", "vi": "Rùa vàng châu Phi", "id": "Kura-kura Sulcata"}',
 'II', 'VU', 'decreasing',
 ARRAY['SEN','MLI','NER','TCD','SUD','ETH','ERI','DJI'],
 false, '{}',
 ARRAY['live_pet','meat'],
 '{"live_per_animal_usd": {"low": 100, "high": 1200}}'),

-- ── BIRDS (3) ──────────────────────────────────────────────────────────────
('Cacatua moluccensis', 'Salmon-crested Cockatoo',
 '{"id": "Kakatua Seram", "zh": "摩鹿加凤头鹦鹉", "th": "นกแก้วหงอนโมลุกกะ"}',
 'I', 'VU', 'decreasing',
 ARRAY['IDN'],
 false, '{}',
 ARRAY['live_pet'],
 '{"live_per_bird_usd": {"low": 1500, "high": 8000}}'),

('Psittacus erithacus', 'African Grey Parrot',
 '{"th": "นกแก้วแอฟริกาเทา", "vi": "Vẹt xám châu Phi", "zh": "非洲灰鹦鹉"}',
 'I', 'EN', 'decreasing',
 ARRAY['CMR','NGA','COD','COG','GAB','GHA','CIV','GNQ','CAF','UGA'],
 false, '{}',
 ARRAY['live_pet'],
 '{"live_per_bird_usd": {"low": 800, "high": 6000}}'),

('Falco peregrinus', 'Peregrine Falcon',
 '{"th": "เหยี่ยวเพเรกริน", "vi": "Chim cắt lớn", "zh": "游隼", "id": "Elang Peregrine"}',
 'I', 'LC', 'increasing',
 ARRAY['SAU','ARE','QAT','KWT','OMN','PAK','IRQ','AFG','CHN','MNG','RUS','USA','CAN'],
 false, '{}',
 ARRAY['live_falconry','eggs'],
 '{"live_per_bird_usd": {"low": 5000, "high": 100000}}'),

-- ── REPTILES (4) ───────────────────────────────────────────────────────────
('Varanus salvator', 'Water Monitor',
 '{"th": "ตะกวด", "vi": "Kỳ đà nước", "zh": "巨蜥", "id": "Biawak Air"}',
 'II', 'LC', 'decreasing',
 ARRAY['IDN','MYS','THA','VNM','MMR','KHM','LAO','PHL','SGP','BGD','IND','LKA'],
 false, '{}',
 ARRAY['skin_leather','meat','live_pet','traditional_medicine'],
 '{"skin_per_piece_usd": {"low": 20, "high": 150}}'),

('Python reticulatus', 'Reticulated Python',
 '{"th": "งูหลาม", "vi": "Trăn hoa", "zh": "网纹蟒", "id": "Sanca Batik"}',
 'II', 'LC', 'decreasing',
 ARRAY['IDN','MYS','THA','PHL','MMR','VNM','KHM','LAO','SGP'],
 false, '{}',
 ARRAY['skin_leather','handbags','shoes','belts','live_pet','meat'],
 '{"skin_per_meter_usd": {"low": 50, "high": 300}}'),

('Naja naja', 'Indian Cobra',
 '{"th": "งูเห่าอินเดีย", "vi": "Rắn hổ mang Ấn Độ", "zh": "印度眼镜蛇", "id": "Ular Kobra India"}',
 'II', 'LC', 'decreasing',
 ARRAY['IND','PAK','BGD','LKA','NPL','MMR','THA','VNM','CHN'],
 false, '{}',
 ARRAY['venom','skin','traditional_medicine','live_pet','meat'],
 '{"venom_per_gram_usd": {"low": 10, "high": 60}}'),

('Eublepharis macularius', 'Leopard Gecko',
 '{"th": "กิ้งก่าเสือดาว", "vi": "Thằn lằn báo", "zh": "豹纹守宫", "id": "Gecko Macan"}',
 'II', 'LC', 'stable',
 ARRAY['PAK','AFG','IND','IRN','NEP'],
 false, '{}',
 ARRAY['live_pet'],
 '{"live_per_animal_usd": {"low": 50, "high": 2000}}'),

-- ── BEARS (2) ──────────────────────────────────────────────────────────────
('Ursus thibetanus', 'Asiatic Black Bear',
 '{"th": "หมีดำเอเชีย", "vi": "Gấu đen châu Á", "zh": "亚洲黑熊", "id": "Beruang Hitam Asia"}',
 'I', 'VU', 'decreasing',
 ARRAY['CHN','RUS','VNM','LAO','KHM','THA','MMR','IND','NPL','BTN','BGD','MYS','IDN','KOR','JPN'],
 false, '{}',
 ARRAY['bile','gallbladder','paw','meat','skin','live_bile_farm'],
 '{"bile_per_gram_usd": {"low": 2, "high": 25}, "gallbladder_usd": {"low": 500, "high": 5000}}'),

('Helarctos malayanus', 'Sun Bear',
 '{"th": "หมีหมา", "vi": "Gấu chó", "zh": "马来熊", "id": "Beruang Madu"}',
 'I', 'VU', 'decreasing',
 ARRAY['IDN','MYS','THA','VNM','CHN','MMR','LAO','KHM','BGD','IND'],
 false, '{}',
 ARRAY['bile','gallbladder','paw','meat','skin','live_pet'],
 '{"bile_per_gram_usd": {"low": 2, "high": 30}}'),

-- ── SHARKS (2) ─────────────────────────────────────────────────────────────
('Rhincodon typus', 'Whale Shark',
 '{"th": "ฉลามวาฬ", "vi": "Cá mập voi", "zh": "鲸鲨", "id": "Hiu Paus"}',
 'II', 'EN', 'decreasing',
 ARRAY['IND','IDN','PHL','AUS','MEX','MOZ','MYS','CHN','TZA'],
 false, '{}',
 ARRAY['fins','liver_oil','meat','skin'],
 '{"fins_per_kg_usd": {"low": 50, "high": 400}}'),

('Carcharhinus falciformis', 'Silky Shark',
 '{"th": "ฉลามไหม", "vi": "Cá mập lụa", "zh": "镰状真鲨", "id": "Hiu Sutera"}',
 'II', 'VU', 'decreasing',
 ARRAY['PHL','IDN','TWN','MEX','ESP','PRT','USA','BRA','KEN','TZA','ZAF'],
 false, '{}',
 ARRAY['fins_dried','fins_soup','liver_oil'],
 '{"fins_per_kg_usd": {"low": 30, "high": 300}}'),

-- ── CORALS (1) ─────────────────────────────────────────────────────────────
('Corallium rubrum', 'Red Coral',
 '{"th": "ปะการังแดง", "vi": "San hô đỏ", "zh": "红珊瑚", "id": "Koral Merah"}',
 'III', 'LC', 'decreasing',
 ARRAY['ITA','ESP','FRA','TUN','MAR','DZA','TUR','GRC','HRV','MLT'],
 false, '{}',
 ARRAY['jewelry','carved_ornament','beads','raw_branch'],
 '{"jewelry_per_piece_usd": {"low": 50, "high": 5000}}'),

-- ── ROSEWOODS (2) ──────────────────────────────────────────────────────────
('Dalbergia cochinchinensis', 'Siamese Rosewood',
 '{"th": "พะยูง", "vi": "Gỗ trắc", "zh": "交趾黄檀", "id": "Rosewood Siam"}',
 'I', 'EN', 'decreasing',
 ARRAY['THA','VNM','KHM','LAO'],
 false, '{}',
 ARRAY['timber_log','sawn_timber','furniture','handicraft','veneer'],
 '{"log_per_m3_usd": {"low": 10000, "high": 50000}}'),

('Dalbergia nigra', 'Brazilian Rosewood',
 '{"zh": "巴西黑黄檀", "vi": "Gỗ hồng mộc Brazil"}',
 'I', 'EN', 'decreasing',
 ARRAY['BRA'],
 false, '{}',
 ARRAY['guitar_back_sides','furniture','veneer','turned_objects'],
 '{"log_per_m3_usd": {"low": 8000, "high": 40000}}'),

-- ── SEAHORSES (1) ──────────────────────────────────────────────────────────
('Hippocampus trimaculatus', 'Three-spot Seahorse',
 '{"th": "ม้าน้ำสามจุด", "vi": "Cá ngựa đốm", "zh": "三斑海马", "id": "Kuda Laut Tiga Bercak"}',
 'II', 'VU', 'decreasing',
 ARRAY['IND','IDN','MYS','THA','VNM','PHL','CHN','AUS'],
 false, '{}',
 ARRAY['dried_whole','traditional_medicine_powder'],
 '{"dried_per_kg_usd": {"low": 200, "high": 1200}}'),

-- ── OTTERS (2) ─────────────────────────────────────────────────────────────
('Lutra lutra', 'Eurasian Otter',
 '{"th": "นากยูเรเชีย", "vi": "Rái cá thường", "zh": "欧亚水獭", "id": "Berang-berang Eurasia"}',
 'I', 'NT', 'decreasing',
 ARRAY['GBR','DEU','FRA','ESP','CHN','RUS','IND','VNM','THA','IDN','MYS','KOR','JPN'],
 false, '{}',
 ARRAY['live_pet','fur','pelt'],
 '{"live_per_animal_usd": {"low": 500, "high": 5000}}'),

('Aonyx cinereus', 'Asian Small-clawed Otter',
 '{"th": "นากเล็บสั้น", "vi": "Rái cá vuốt nhỏ", "zh": "小爪水獭", "id": "Berang-berang Cakar Kecil"}',
 'I', 'VU', 'decreasing',
 ARRAY['IDN','MYS','THA','VNM','CHN','MMR','LAO','KHM','IND','BGD'],
 false, '{}',
 ARRAY['live_pet','fur'],
 '{"live_per_animal_usd": {"low": 800, "high": 6000}}'),

-- ── SLOW LORISES (2) ───────────────────────────────────────────────────────
('Nycticebus coucang', 'Sunda Slow Loris',
 '{"th": "ลิงลมซุนดา", "vi": "Cu li lớn", "zh": "蜂猴", "id": "Kukang Sunda"}',
 'I', 'EN', 'decreasing',
 ARRAY['IDN','MYS','THA','SGP','VNM'],
 false, '{}',
 ARRAY['live_pet','traditional_medicine','fur'],
 '{"live_per_animal_usd": {"low": 200, "high": 2000}}'),

('Nycticebus pygmaeus', 'Pygmy Slow Loris',
 '{"th": "ลิงลมแคระ", "vi": "Cu li nhỏ", "zh": "小蜂猴", "id": "Kukang Pygmy"}',
 'I', 'EN', 'decreasing',
 ARRAY['VNM','LAO','KHM','CHN','MMR'],
 false, '{}',
 ARRAY['live_pet','traditional_medicine'],
 '{"live_per_animal_usd": {"low": 150, "high": 1500}}'),

-- ── GECKOS (2) ─────────────────────────────────────────────────────────────
('Gekko gecko', 'Tokay Gecko',
 '{"th": "ตุ๊กแกบ้าน", "vi": "Tắc kè hoa", "zh": "大壁虎", "id": "Tokek"}',
 'II', 'LC', 'decreasing',
 ARRAY['THA','VNM','IDN','PHL','CHN','MMR','LAO','KHM','MYS','IND'],
 false, '{}',
 ARRAY['dried_whole','traditional_medicine','live_pet','tincture'],
 '{"dried_per_pair_usd": {"low": 20, "high": 500}, "large_dried_usd": {"low": 500, "high": 5000}}'),

('Uroplatus fimbriatus', 'Giant Leaf-tail Gecko',
 '{"zh": "大叶尾壁虎", "vi": "Thạch sùng đuôi lá khổng lồ"}',
 'II', 'NT', 'decreasing',
 ARRAY['MDG'],
 false, '{}',
 ARRAY['live_pet'],
 '{"live_per_animal_usd": {"low": 200, "high": 2000}}'),

-- ── STAR TORTOISE (1) ──────────────────────────────────────────────────────
('Geochelone platynota', 'Burmese Star Tortoise',
 '{"th": "เต่าดาวพม่า", "vi": "Rùa sao Myanmar", "zh": "缅甸星龟", "id": "Kura-kura Bintang Burma"}',
 'I', 'CR', 'decreasing',
 ARRAY['MMR'],
 false, '{}',
 ARRAY['live_pet','shell_ornament'],
 '{"live_per_animal_usd": {"low": 500, "high": 5000}}'),

-- ── AROWANA (1) ────────────────────────────────────────────────────────────
('Scleropages formosus', 'Asian Arowana',
 '{"th": "ปลามังกร", "vi": "Cá rồng châu Á", "zh": "亚洲龙鱼", "id": "Arwana Asia"}',
 'I', 'EN', 'decreasing',
 ARRAY['IDN','MYS','THA','VNM','MMR','KHM'],
 false, '{}',
 ARRAY['live_pet'],
 '{"live_per_fish_usd": {"low": 300, "high": 300000}}'),

-- ── GIBBONS (1) ────────────────────────────────────────────────────────────
('Nomascus gabriellae', 'Yellow-cheeked Gibbon',
 '{"vi": "Vượn má vàng", "th": "ชะนีแก้มเหลือง", "zh": "黄颊长臂猿"}',
 'I', 'EN', 'decreasing',
 ARRAY['VNM','KHM','LAO'],
 false, '{}',
 ARRAY['live_pet','meat'],
 '{"live_per_animal_usd": {"low": 1000, "high": 8000}}'),

-- ── SAIGA (1) ──────────────────────────────────────────────────────────────
('Saiga tatarica', 'Saiga Antelope',
 '{"zh": "赛加羚羊", "vi": "Linh dương Saiga"}',
 'I', 'CR', 'decreasing',
 ARRAY['KAZ','RUS','MNG','UZB','TKM'],
 false, '{}',
 ARRAY['horn_powder','traditional_medicine','meat'],
 '{"horn_per_kg_usd": {"low": 500, "high": 3000}}'),

-- ── SNOW LEOPARD (1) ───────────────────────────────────────────────────────
('Panthera uncia', 'Snow Leopard',
 '{"th": "เสือหิมะ", "vi": "Báo tuyết", "zh": "雪豹", "id": "Macan Tutul Salju"}',
 'I', 'VU', 'decreasing',
 ARRAY['CHN','MNG','RUS','KGZ','TJK','AFG','PAK','IND','NPL','BTN','UZB','KAZ'],
 false, '{}',
 ARRAY['skin_pelt','bone','fur_coat','live'],
 '{"pelt_usd": {"low": 5000, "high": 20000}}'),

-- ── CLOUDED LEOPARD (1) ────────────────────────────────────────────────────
('Neofelis nebulosa', 'Clouded Leopard',
 '{"th": "เสือลายเมฆ", "vi": "Báo gấm", "zh": "云豹", "id": "Macan Dahan"}',
 'I', 'VU', 'decreasing',
 ARRAY['CHN','IND','MMR','THA','VNM','LAO','KHM','MYS','NPL','BGD','BTN'],
 false, '{}',
 ARRAY['skin_pelt','teeth','claws','bone','live'],
 '{"pelt_usd": {"low": 3000, "high": 15000}}'),

-- ── GAUR (1) ───────────────────────────────────────────────────────────────
('Bos gaurus', 'Gaur',
 '{"th": "กระทิง", "vi": "Bò tót", "zh": "印度野牛", "id": "Gaur"}',
 'I', 'VU', 'decreasing',
 ARRAY['IND','MMR','THA','VNM','LAO','KHM','MYS','CHN','NEP','BTN'],
 false, '{}',
 ARRAY['meat','horn','hide','trophy'],
 '{"horn_pair_usd": {"low": 200, "high": 1500}}'),

-- ── ORCHIDS (1) ────────────────────────────────────────────────────────────
('Dendrobium devonianum', 'Devon Dendrobium',
 '{"th": "กล้วยไม้หวาย", "vi": "Lan hoàng thảo", "zh": "肿节石斛"}',
 'II', 'LC', 'decreasing',
 ARRAY['IND','CHN','THA','MMR','VNM','LAO','NEP','BTN'],
 false, '{}',
 ARRAY['live_plant','dried_stem_medicine','cut_flower'],
 '{"live_plant_usd": {"low": 10, "high": 500}}'),

-- ── HUMPHEAD WRASSE (1) ────────────────────────────────────────────────────
('Cheilinus undulatus', 'Humphead Wrasse',
 '{"th": "ปลานโปเลียน", "vi": "Cá mó đầu u", "zh": "苏眉鱼", "id": "Ikan Napoleon"}',
 'II', 'EN', 'decreasing',
 ARRAY['IDN','PHL','AUS','MYS','PNG','SLB','FJI','PLW','FSM','THA','VNM','CHN'],
 false, '{}',
 ARRAY['live_reef_fish','fillet','live_food_fish'],
 '{"live_per_fish_usd": {"low": 300, "high": 2000}}'),

-- ── MUSK DEER (1) ──────────────────────────────────────────────────────────
('Moschus moschiferus', 'Siberian Musk Deer',
 '{"th": "กวางชะมด", "vi": "Hươu xạ Siberia", "zh": "原麝", "id": "Rusa Kasturi Siberia"}',
 'I', 'VU', 'decreasing',
 ARRAY['RUS','CHN','MNG','KAZ','KGZ','TJK'],
 false, '{}',
 ARRAY['musk_pod','musk_powder','traditional_medicine','perfume_ingredient'],
 '{"musk_per_gram_usd": {"low": 45, "high": 500}}'),

-- ── KING COBRA (1) ─────────────────────────────────────────────────────────
('Ophiophagus hannah', 'King Cobra',
 '{"th": "งูจงอาง", "vi": "Rắn hổ chúa", "zh": "眼镜王蛇", "id": "Ular Raja Kobra"}',
 'II', 'VU', 'decreasing',
 ARRAY['IND','CHN','THA','VNM','IDN','PHL','MYS','MMR','LAO','KHM','BGD','SGP'],
 false, '{}',
 ARRAY['venom','skin_leather','meat','live_pet','traditional_medicine','wine'],
 '{"live_per_animal_usd": {"low": 100, "high": 1500}, "venom_per_gram_usd": {"low": 5, "high": 40}}'),

-- ── SOFTSHELL TURTLE (1) ───────────────────────────────────────────────────
('Pelochelys cantorii', 'Asian Giant Softshell Turtle',
 '{"th": "เต่านิ่มยักษ์", "vi": "Rùa mai mềm khổng lồ", "zh": "亚洲巨型鳖", "id": "Kura-kura Labi-labi Raksasa"}',
 'II', 'CR', 'decreasing',
 ARRAY['IND','BGD','THA','VNM','IDN','PHL','MYS','KHM','MMR','CHN'],
 false, '{}',
 ARRAY['meat','eggs','shell','traditional_medicine'],
 '{"meat_per_kg_usd": {"low": 20, "high": 120}, "live_per_animal_usd": {"low": 500, "high": 4000}}'),

-- ── ADDITIONAL HIGH-PRIORITY SPECIES ───────────────────────────────────────

('Panthera pardus', 'Leopard',
 '{"th": "เสือดาว", "vi": "Báo hoa mai", "zh": "豹", "id": "Macan Tutul"}',
 'I', 'VU', 'decreasing',
 ARRAY['IND','CHN','RUS','ZAF','KEN','TZA','ETH','ZWE','SOM','SSD','UGA','NAM','MOZ','BWA','ZMB','ZAR','CMR','NGA','GHA','SEN'],
 false, '{}',
 ARRAY['skin_pelt','teeth','claws','bone','live'],
 '{"pelt_usd": {"low": 3000, "high": 18000}}'),

('Crocodylus siamensis', 'Siamese Crocodile',
 '{"th": "จระเข้สยาม", "vi": "Cá sấu Xiêm", "zh": "暹罗鳄", "id": "Buaya Siam"}',
 'I', 'CR', 'decreasing',
 ARRAY['THA','KHM','LAO','VNM','IDN','MYS'],
 false, '{}',
 ARRAY['skin_leather','handbag','belt','shoes','meat','live'],
 '{"skin_per_piece_usd": {"low": 200, "high": 3000}}'),

('Macaca fascicularis', 'Long-tailed Macaque',
 '{"th": "ลิงแสม", "vi": "Khỉ đuôi dài", "zh": "食蟹猕猴", "id": "Monyet Ekor Panjang"}',
 'II', 'EN', 'decreasing',
 ARRAY['IDN','MYS','THA','PHL','VNM','KHM','LAO','MMR','SGP','BGD'],
 false, '{}',
 ARRAY['live_research','live_pet','bushmeat'],
 '{"live_per_animal_usd": {"low": 200, "high": 3000}}'),

('Pavo muticus', 'Green Peafowl',
 '{"th": "นกยูงเขียว", "vi": "Công xanh", "zh": "绿孔雀", "id": "Merak Hijau"}',
 'I', 'EN', 'decreasing',
 ARRAY['IDN','THA','VNM','MMR','LAO','KHM','CHN','IND'],
 false, '{}',
 ARRAY['live_pet','feathers','meat'],
 '{"live_per_bird_usd": {"low": 300, "high": 3000}}'),

('Rhinopithecus roxellana', 'Golden Snub-nosed Monkey',
 '{"zh": "金丝猴", "vi": "Khỉ mũi hếch vàng"}',
 'I', 'EN', 'decreasing',
 ARRAY['CHN'],
 false, '{}',
 ARRAY['live_pet','fur','traditional_medicine'],
 '{"live_per_animal_usd": {"low": 2000, "high": 15000}}');
