-- 006b: LLM analysis updates for yellow-scoring listings
-- GPT-4o Vision + translation + recalculated scores
-- Generated: 2026-03-30 00:31:11

UPDATE listings SET title_translated = 'Ivory necklace, Micron gold' WHERE id = 'd0000000-0000-0000-0000-000000000096';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": true, "predicted_product": "ivory", "confidence": 0.85, "visual_evidence": "The beads have a creamy color and smooth texture typical of carved ivory.", "alternative_explanations": "The beads could be made from bone or a synthetic material designed to mimic ivory.", "predicted_species": "Elephantidae"}, "per_image_results": [{"product_detected": true, "predicted_product": "ivory", "confidence": 0.85, "visual_evidence": "The beads have a creamy color and smooth texture typical of carved ivory.", "alternative_explanations": "The beads could be made from bone or a synthetic material designed to mimic ivory.", "predicted_species": "Elephantidae"}], "image_risk_score": 0.85}'::jsonb, image_risk_score = 0.85, text_image_agreement = 'agree', risk_score = 81, alert_tier = 'red', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 10, "max": 12}, "seizure": {"score": 8, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 12, "max": 12}}'::jsonb, agreement_bonus = 5 WHERE listing_id = 'd0000000-0000-0000-0000-000000000096';

UPDATE listings SET title_translated = 'Open,, the image you see is a carved tiger fang, which is an amulet that has been r?' WHERE id = 'd0000000-0000-0000-0000-000000000138';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": false, "predicted_product": null, "predicted_species": null, "confidence": 0.0, "visual_evidence": "Image analysis failed", "alternative_explanations": null}, "per_image_results": [], "image_risk_score": 0.0}'::jsonb, image_risk_score = 0.0, text_image_agreement = 'disagree', risk_score = 64, alert_tier = 'amber', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 10, "max": 12}, "seizure": {"score": 8, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 0, "max": 12}}'::jsonb, agreement_bonus = 0 WHERE listing_id = 'd0000000-0000-0000-0000-000000000138';

UPDATE listings SET title_translated = 'Genuine ivory' WHERE id = 'd0000000-0000-0000-0000-000000000097';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": true, "predicted_product": "ivory", "confidence": 0.95, "visual_evidence": "The image shows two large, curved, light-colored tusks mounted on stands, resembling elephant ivory.", "alternative_explanations": "The tusks could be replicas made from synthetic materials or bone, but the size and color are typical of elephant ivory.", "predicted_species": "Loxodonta africana or Elephas maximus"}, "per_image_results": [{"product_detected": true, "predicted_product": "ivory", "confidence": 0.95, "visual_evidence": "The image shows two large, curved, light-colored tusks mounted on stands, resembling elephant ivory.", "alternative_explanations": "The tusks could be replicas made from synthetic materials or bone, but the size and color are typical of elephant ivory.", "predicted_species": "Loxodonta africana or Elephas maximus"}], "image_risk_score": 0.95}'::jsonb, image_risk_score = 0.95, text_image_agreement = 'agree', risk_score = 81, alert_tier = 'red', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 10, "max": 12}, "seizure": {"score": 8, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 12, "max": 12}}'::jsonb, agreement_bonus = 5 WHERE listing_id = 'd0000000-0000-0000-0000-000000000097';

UPDATE listings SET title_translated = 'Ivory wood' WHERE id = 'd0000000-0000-0000-0000-000000000098';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": false, "predicted_product": null, "confidence": 0.95, "visual_evidence": "The image shows wooden planks.", "alternative_explanations": "The product could be regular lumber or construction wood.", "predicted_species": null}, "per_image_results": [{"product_detected": false, "predicted_product": null, "confidence": 0.95, "visual_evidence": "The image shows wooden planks.", "alternative_explanations": "The product could be regular lumber or construction wood.", "predicted_species": null}], "image_risk_score": 0.0}'::jsonb, image_risk_score = 0.0, text_image_agreement = 'disagree', risk_score = 64, alert_tier = 'amber', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 10, "max": 12}, "seizure": {"score": 8, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 0, "max": 12}}'::jsonb, agreement_bonus = 0 WHERE listing_id = 'd0000000-0000-0000-0000-000000000098';

UPDATE listings SET title_translated = 'Elephant ivory necklace, 111 prayer beads.' WHERE id = 'd0000000-0000-0000-0000-000000000099';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": true, "predicted_product": "ivory", "confidence": 0.85, "visual_evidence": "The necklace features a carved elephant pendant and beads that resemble ivory in color and texture.", "alternative_explanations": "The material could be bone, resin, or a synthetic material designed to mimic ivory.", "predicted_species": "Elephantidae"}, "per_image_results": [{"product_detected": true, "predicted_product": "ivory", "confidence": 0.85, "visual_evidence": "The necklace features a carved elephant pendant and beads that resemble ivory in color and texture.", "alternative_explanations": "The material could be bone, resin, or a synthetic material designed to mimic ivory.", "predicted_species": "Elephantidae"}], "image_risk_score": 0.85}'::jsonb, image_risk_score = 0.85, text_image_agreement = 'agree', risk_score = 81, alert_tier = 'red', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 10, "max": 12}, "seizure": {"score": 8, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 12, "max": 12}}'::jsonb, agreement_bonus = 5 WHERE listing_id = 'd0000000-0000-0000-0000-000000000099';

UPDATE listings SET title_translated = 'Old ivory necklace with a small Phra Pho Niam amulet.' WHERE id = 'd0000000-0000-0000-0000-000000000100';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": false, "predicted_product": null, "confidence": 0.0, "visual_evidence": "The image shows a beaded necklace with a pendant. The beads appear to be wooden or plastic, and the pendant is encased in a green frame.", "alternative_explanations": "The necklace could be made from common materials such as wood, plastic, or metal, none of which are CITES-listed.", "predicted_species": null}, "per_image_results": [{"product_detected": false, "predicted_product": null, "confidence": 0.0, "visual_evidence": "The image shows a beaded necklace with a pendant. The beads appear to be wooden or plastic, and the pendant is encased in a green frame.", "alternative_explanations": "The necklace could be made from common materials such as wood, plastic, or metal, none of which are CITES-listed.", "predicted_species": null}], "image_risk_score": 0.0}'::jsonb, image_risk_score = 0.0, text_image_agreement = 'disagree', risk_score = 64, alert_tier = 'amber', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 10, "max": 12}, "seizure": {"score": 8, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 0, "max": 12}}'::jsonb, agreement_bonus = 0 WHERE listing_id = 'd0000000-0000-0000-0000-000000000100';

UPDATE listings SET title_translated = 'Elephant ivory talisman, unknown monk.' WHERE id = 'd0000000-0000-0000-0000-000000000101';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": true, "predicted_product": "ivory", "confidence": 0.85, "visual_evidence": "The image shows a smooth, white material with carved patterns, typical of ivory.", "alternative_explanations": "The material could also be bone or a synthetic imitation designed to resemble ivory.", "predicted_species": "Loxodonta africana or Elephas maximus"}, "per_image_results": [{"product_detected": true, "predicted_product": "ivory", "confidence": 0.85, "visual_evidence": "The image shows a smooth, white material with carved patterns, typical of ivory.", "alternative_explanations": "The material could also be bone or a synthetic imitation designed to resemble ivory.", "predicted_species": "Loxodonta africana or Elephas maximus"}], "image_risk_score": 0.85}'::jsonb, image_risk_score = 0.85, text_image_agreement = 'agree', risk_score = 81, alert_tier = 'red', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 10, "max": 12}, "seizure": {"score": 8, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 12, "max": 12}}'::jsonb, agreement_bonus = 5 WHERE listing_id = 'd0000000-0000-0000-0000-000000000101';

UPDATE listings SET title_translated = 'Tiger?? Carved Ivory' WHERE id = 'd0000000-0000-0000-0000-000000000102';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": true, "predicted_product": "carved ivory", "confidence": 0.85, "visual_evidence": "The item appears to be a small, carved piece with a smooth, creamy texture typical of ivory.", "alternative_explanations": "The item could also be bone or a synthetic material designed to mimic ivory.", "predicted_species": "Elephantidae"}, "per_image_results": [{"product_detected": true, "predicted_product": "carved ivory", "confidence": 0.85, "visual_evidence": "The item appears to be a small, carved piece with a smooth, creamy texture typical of ivory.", "alternative_explanations": "The item could also be bone or a synthetic material designed to mimic ivory.", "predicted_species": "Elephantidae"}], "image_risk_score": 0.85}'::jsonb, image_risk_score = 0.85, text_image_agreement = 'agree', risk_score = 81, alert_tier = 'red', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 10, "max": 12}, "seizure": {"score": 8, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 12, "max": 12}}'::jsonb, agreement_bonus = 5 WHERE listing_id = 'd0000000-0000-0000-0000-000000000102';

UPDATE listings SET title_translated = 'Hanuman ivory amulet with inscriptions by Father Sun.' WHERE id = 'd0000000-0000-0000-0000-000000000103';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": true, "predicted_product": "carved ivory", "confidence": 0.85, "visual_evidence": "The product appears to be a small carved figure with a creamy color and fine grain patterns typical of ivory.", "alternative_explanations": "The material could also be bone or a synthetic material designed to mimic ivory.", "predicted_species": "Elephantidae"}, "per_image_results": [{"product_detected": true, "predicted_product": "carved ivory", "confidence": 0.85, "visual_evidence": "The product appears to be a small carved figure with a creamy color and fine grain patterns typical of ivory.", "alternative_explanations": "The material could also be bone or a synthetic material designed to mimic ivory.", "predicted_species": "Elephantidae"}], "image_risk_score": 0.85}'::jsonb, image_risk_score = 0.85, text_image_agreement = 'agree', risk_score = 81, alert_tier = 'red', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 10, "max": 12}, "seizure": {"score": 8, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 12, "max": 12}}'::jsonb, agreement_bonus = 5 WHERE listing_id = 'd0000000-0000-0000-0000-000000000103';

UPDATE listings SET title_translated = 'Water elephant ivory' WHERE id = 'd0000000-0000-0000-0000-000000000104';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": true, "predicted_product": "ivory", "confidence": 0.85, "visual_evidence": "The image shows a smooth, curved, and pointed object resembling a tusk.", "alternative_explanations": "The object could be a synthetic replica or a bone carving.", "predicted_species": "Loxodonta africana or Elephas maximus"}, "per_image_results": [{"product_detected": true, "predicted_product": "ivory", "confidence": 0.85, "visual_evidence": "The image shows a smooth, curved, and pointed object resembling a tusk.", "alternative_explanations": "The object could be a synthetic replica or a bone carving.", "predicted_species": "Loxodonta africana or Elephas maximus"}], "image_risk_score": 0.85}'::jsonb, image_risk_score = 0.85, text_image_agreement = 'agree', risk_score = 81, alert_tier = 'red', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 10, "max": 12}, "seizure": {"score": 8, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 12, "max": 12}}'::jsonb, agreement_bonus = 5 WHERE listing_id = 'd0000000-0000-0000-0000-000000000104';

UPDATE listings SET title_translated = 'Genuine ivory necklace' WHERE id = 'd0000000-0000-0000-0000-000000000105';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": true, "predicted_product": "ivory", "confidence": 0.85, "visual_evidence": "The beads have a smooth, creamy appearance with a fine grain pattern typical of carved ivory.", "alternative_explanations": "The beads could be made from bone or a synthetic material designed to mimic ivory.", "predicted_species": "Elephantidae"}, "per_image_results": [{"product_detected": true, "predicted_product": "ivory", "confidence": 0.85, "visual_evidence": "The beads have a smooth, creamy appearance with a fine grain pattern typical of carved ivory.", "alternative_explanations": "The beads could be made from bone or a synthetic material designed to mimic ivory.", "predicted_species": "Elephantidae"}], "image_risk_score": 0.85}'::jsonb, image_risk_score = 0.85, text_image_agreement = 'agree', risk_score = 81, alert_tier = 'red', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 10, "max": 12}, "seizure": {"score": 8, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 12, "max": 12}}'::jsonb, agreement_bonus = 5 WHERE listing_id = 'd0000000-0000-0000-0000-000000000105';

UPDATE listings SET title_translated = 'Ivory ring' WHERE id = 'd0000000-0000-0000-0000-000000000107';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": true, "predicted_product": "ivory", "confidence": 0.85, "visual_evidence": "The product appears to be a ring with a large, smooth, off-white material resembling carved ivory.", "alternative_explanations": "The material could also be bone, resin, or another synthetic material designed to mimic ivory.", "predicted_species": "Elephantidae"}, "per_image_results": [{"product_detected": true, "predicted_product": "ivory", "confidence": 0.85, "visual_evidence": "The product appears to be a ring with a large, smooth, off-white material resembling carved ivory.", "alternative_explanations": "The material could also be bone, resin, or another synthetic material designed to mimic ivory.", "predicted_species": "Elephantidae"}], "image_risk_score": 0.85}'::jsonb, image_risk_score = 0.85, text_image_agreement = 'agree', risk_score = 81, alert_tier = 'red', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 10, "max": 12}, "seizure": {"score": 8, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 12, "max": 12}}'::jsonb, agreement_bonus = 5 WHERE listing_id = 'd0000000-0000-0000-0000-000000000107';

UPDATE listings SET title_translated = 'Ivory buckle carved with a tiger head design by Master Chaiwat.' WHERE id = 'd0000000-0000-0000-0000-000000000108';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": true, "predicted_product": "ivory", "confidence": 0.85, "visual_evidence": "The product appears to be a carved piece with a tiger illustration, typical of ivory''s smooth texture and color.", "alternative_explanations": "The material could be a synthetic or bone imitation designed to resemble ivory.", "predicted_species": "Elephantidae"}, "per_image_results": [{"product_detected": true, "predicted_product": "ivory", "confidence": 0.85, "visual_evidence": "The product appears to be a carved piece with a tiger illustration, typical of ivory''s smooth texture and color.", "alternative_explanations": "The material could be a synthetic or bone imitation designed to resemble ivory.", "predicted_species": "Elephantidae"}], "image_risk_score": 0.85}'::jsonb, image_risk_score = 0.85, text_image_agreement = 'agree', risk_score = 81, alert_tier = 'red', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 10, "max": 12}, "seizure": {"score": 8, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 12, "max": 12}}'::jsonb, agreement_bonus = 5 WHERE listing_id = 'd0000000-0000-0000-0000-000000000108';

UPDATE listings SET title_translated = 'Elephant Tusk Betel Leaf' WHERE id = 'd0000000-0000-0000-0000-000000000109';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": false, "predicted_product": null, "confidence": 0.0, "visual_evidence": "The image shows a plant with green and white variegated leaves.", "alternative_explanations": "This is a common houseplant, possibly a type of pothos or philodendron.", "predicted_species": null}, "per_image_results": [{"product_detected": false, "predicted_product": null, "confidence": 0.0, "visual_evidence": "The image shows a plant with green and white variegated leaves.", "alternative_explanations": "This is a common houseplant, possibly a type of pothos or philodendron.", "predicted_species": null}], "image_risk_score": 0.0}'::jsonb, image_risk_score = 0.0, text_image_agreement = 'disagree', risk_score = 64, alert_tier = 'amber', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 10, "max": 12}, "seizure": {"score": 8, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 0, "max": 12}}'::jsonb, agreement_bonus = 0 WHERE listing_id = 'd0000000-0000-0000-0000-000000000109';

UPDATE listings SET title_translated = 'Phra Somdej carved from ivory, old collection, beautiful work, 9-tiered base print.' WHERE id = 'd0000000-0000-0000-0000-000000000110';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": true, "predicted_product": "ivory", "confidence": 0.85, "visual_evidence": "The product appears to be a carved object with a smooth, creamy texture typical of ivory.", "alternative_explanations": "The material could also be bone or a synthetic material designed to mimic ivory.", "predicted_species": "Elephantidae"}, "per_image_results": [{"product_detected": true, "predicted_product": "ivory", "confidence": 0.85, "visual_evidence": "The product appears to be a carved object with a smooth, creamy texture typical of ivory.", "alternative_explanations": "The material could also be bone or a synthetic material designed to mimic ivory.", "predicted_species": "Elephantidae"}], "image_risk_score": 0.85}'::jsonb, image_risk_score = 0.85, text_image_agreement = 'agree', risk_score = 81, alert_tier = 'red', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 10, "max": 12}, "seizure": {"score": 8, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 12, "max": 12}}'::jsonb, agreement_bonus = 5 WHERE listing_id = 'd0000000-0000-0000-0000-000000000110';

UPDATE listings SET title_translated = 'Luang Por Derm Elephant Ivory, First Edition' WHERE id = 'd0000000-0000-0000-0000-000000000111';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": true, "predicted_product": "ivory", "confidence": 0.85, "visual_evidence": "The pendant has a yellowish hue and fine grain patterns typical of carved ivory.", "alternative_explanations": "The material could also be bone or a synthetic imitation designed to resemble ivory.", "predicted_species": "Elephantidae"}, "per_image_results": [{"product_detected": true, "predicted_product": "ivory", "confidence": 0.85, "visual_evidence": "The pendant has a yellowish hue and fine grain patterns typical of carved ivory.", "alternative_explanations": "The material could also be bone or a synthetic imitation designed to resemble ivory.", "predicted_species": "Elephantidae"}], "image_risk_score": 0.85}'::jsonb, image_risk_score = 0.85, text_image_agreement = 'agree', risk_score = 81, alert_tier = 'red', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 10, "max": 12}, "seizure": {"score": 8, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 12, "max": 12}}'::jsonb, agreement_bonus = 5 WHERE listing_id = 'd0000000-0000-0000-0000-000000000111';

UPDATE listings SET title_translated = 'Black elephant tusk ring core, inside contains genuine silver iron wire, 100% authentic.' WHERE id = 'd0000000-0000-0000-0000-000000000117';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": false, "predicted_product": null, "confidence": 0.0, "visual_evidence": "The object appears to be a polished, dark stone with visible veins or patterns.", "alternative_explanations": "This could be a gemstone or a polished mineral.", "predicted_species": null}, "per_image_results": [{"product_detected": false, "predicted_product": null, "confidence": 0.0, "visual_evidence": "The object appears to be a polished, dark stone with visible veins or patterns.", "alternative_explanations": "This could be a gemstone or a polished mineral.", "predicted_species": null}], "image_risk_score": 0.0}'::jsonb, image_risk_score = 0.0, text_image_agreement = 'disagree', risk_score = 64, alert_tier = 'amber', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 10, "max": 12}, "seizure": {"score": 8, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 0, "max": 12}}'::jsonb, agreement_bonus = 0 WHERE listing_id = 'd0000000-0000-0000-0000-000000000117';

UPDATE listings SET title_translated = 'Genuine Tortoiseshell Glasses 🐢🐢' WHERE id = 'd0000000-0000-0000-0000-000000000158';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": false, "predicted_product": null, "predicted_species": null, "confidence": 0.0, "visual_evidence": "Image analysis failed", "alternative_explanations": null}, "per_image_results": [], "image_risk_score": 0.0}'::jsonb, image_risk_score = 0.0, text_image_agreement = 'disagree', risk_score = 57, alert_tier = 'yellow', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 7, "max": 12}, "seizure": {"score": 4, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 0, "max": 12}}'::jsonb, agreement_bonus = 0 WHERE listing_id = 'd0000000-0000-0000-0000-000000000158';

UPDATE listings SET title_translated = 'Genuine tortoiseshell glasses' WHERE id = 'd0000000-0000-0000-0000-000000000148';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": false, "predicted_product": null, "predicted_species": null, "confidence": 0.0, "visual_evidence": "Image analysis failed", "alternative_explanations": null}, "per_image_results": [], "image_risk_score": 0.0}'::jsonb, image_risk_score = 0.0, text_image_agreement = 'disagree', risk_score = 57, alert_tier = 'yellow', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 7, "max": 12}, "seizure": {"score": 4, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 0, "max": 12}}'::jsonb, agreement_bonus = 0 WHERE listing_id = 'd0000000-0000-0000-0000-000000000148';

UPDATE listings SET title_translated = 'Tibetan Stone Bracelet, Green Turtle Shell, 9 Eyes, 8-10 mm.' WHERE id = 'd0000000-0000-0000-0000-000000000141';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": false, "predicted_product": null, "predicted_species": null, "confidence": 0.0, "visual_evidence": "Image analysis failed", "alternative_explanations": null}, "per_image_results": [], "image_risk_score": 0.0}'::jsonb, image_risk_score = 0.0, text_image_agreement = 'disagree', risk_score = 57, alert_tier = 'yellow', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 7, "max": 12}, "seizure": {"score": 4, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 0, "max": 12}}'::jsonb, agreement_bonus = 0 WHERE listing_id = 'd0000000-0000-0000-0000-000000000141';

UPDATE listings SET title_translated = 'Green turquoise bracelet, turtle shell, 12 mm.' WHERE id = 'd0000000-0000-0000-0000-000000000143';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": false, "predicted_product": null, "predicted_species": null, "confidence": 0.0, "visual_evidence": "Image analysis failed", "alternative_explanations": null}, "per_image_results": [], "image_risk_score": 0.0}'::jsonb, image_risk_score = 0.0, text_image_agreement = 'disagree', risk_score = 57, alert_tier = 'yellow', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 7, "max": 12}, "seizure": {"score": 4, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 0, "max": 12}}'::jsonb, agreement_bonus = 0 WHERE listing_id = 'd0000000-0000-0000-0000-000000000143';

UPDATE listings SET title_translated = 'Genuine Tortoiseshell Glasses Frame 💯 Size 54' WHERE id = 'd0000000-0000-0000-0000-000000000144';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": false, "predicted_product": null, "predicted_species": null, "confidence": 0.0, "visual_evidence": "Image analysis failed", "alternative_explanations": null}, "per_image_results": [], "image_risk_score": 0.0}'::jsonb, image_risk_score = 0.0, text_image_agreement = 'disagree', risk_score = 57, alert_tier = 'yellow', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 7, "max": 12}, "seizure": {"score": 4, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 0, "max": 12}}'::jsonb, agreement_bonus = 0 WHERE listing_id = 'd0000000-0000-0000-0000-000000000144';

UPDATE listings SET title_translated = 'Turtle shells, good condition as shown in the picture, selling as a pair for 700.' WHERE id = 'd0000000-0000-0000-0000-000000000145';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": false, "predicted_product": null, "predicted_species": null, "confidence": 0.0, "visual_evidence": "Image analysis failed", "alternative_explanations": null}, "per_image_results": [], "image_risk_score": 0.0}'::jsonb, image_risk_score = 0.0, text_image_agreement = 'disagree', risk_score = 57, alert_tier = 'yellow', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 7, "max": 12}, "seizure": {"score": 4, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 0, "max": 12}}'::jsonb, agreement_bonus = 0 WHERE listing_id = 'd0000000-0000-0000-0000-000000000145';

UPDATE listings SET title_translated = 'Lacquer-coated wooden tray with tortoiseshell pattern made from vintage cherry bark by Cherry Craft.' WHERE id = 'd0000000-0000-0000-0000-000000000146';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": false, "predicted_product": null, "predicted_species": null, "confidence": 0.0, "visual_evidence": "Image analysis failed", "alternative_explanations": null}, "per_image_results": [], "image_risk_score": 0.0}'::jsonb, image_risk_score = 0.0, text_image_agreement = 'disagree', risk_score = 57, alert_tier = 'yellow', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 7, "max": 12}, "seizure": {"score": 4, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 0, "max": 12}}'::jsonb, agreement_bonus = 0 WHERE listing_id = 'd0000000-0000-0000-0000-000000000146';

UPDATE listings SET title_translated = 'Lucky stone bracelet with rainbow-colored turtle shell turquoise, blue, green, red, wizard stone?' WHERE id = 'd0000000-0000-0000-0000-000000000147';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": false, "predicted_product": null, "predicted_species": null, "confidence": 0.0, "visual_evidence": "Image analysis failed", "alternative_explanations": null}, "per_image_results": [], "image_risk_score": 0.0}'::jsonb, image_risk_score = 0.0, text_image_agreement = 'disagree', risk_score = 57, alert_tier = 'yellow', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 7, "max": 12}, "seizure": {"score": 4, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 0, "max": 12}}'::jsonb, agreement_bonus = 0 WHERE listing_id = 'd0000000-0000-0000-0000-000000000147';

UPDATE listings SET title_translated = 'Turtle shell-shaped hat' WHERE id = 'd0000000-0000-0000-0000-000000000149';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": false, "predicted_product": null, "predicted_species": null, "confidence": 0.0, "visual_evidence": "Image analysis failed", "alternative_explanations": null}, "per_image_results": [], "image_risk_score": 0.0}'::jsonb, image_risk_score = 0.0, text_image_agreement = 'disagree', risk_score = 57, alert_tier = 'yellow', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 7, "max": 12}, "seizure": {"score": 4, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 0, "max": 12}}'::jsonb, agreement_bonus = 0 WHERE listing_id = 'd0000000-0000-0000-0000-000000000149';

UPDATE listings SET title_translated = 'Tortoiseshell glasses frame Frame Japan Titan-P' WHERE id = 'd0000000-0000-0000-0000-000000000150';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": false, "predicted_product": null, "predicted_species": null, "confidence": 0.0, "visual_evidence": "Image analysis failed", "alternative_explanations": null}, "per_image_results": [], "image_risk_score": 0.0}'::jsonb, image_risk_score = 0.0, text_image_agreement = 'disagree', risk_score = 57, alert_tier = 'yellow', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 7, "max": 12}, "seizure": {"score": 4, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 0, "max": 12}}'::jsonb, agreement_bonus = 0 WHERE listing_id = 'd0000000-0000-0000-0000-000000000150';

UPDATE listings SET title_translated = 'Adamas 1581-5, large turtle shell back, great sound with a unique character, beautiful condition that captivates.' WHERE id = 'd0000000-0000-0000-0000-000000000151';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": false, "predicted_product": null, "predicted_species": null, "confidence": 0.0, "visual_evidence": "Image analysis failed", "alternative_explanations": null}, "per_image_results": [], "image_risk_score": 0.0}'::jsonb, image_risk_score = 0.0, text_image_agreement = 'disagree', risk_score = 57, alert_tier = 'yellow', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 7, "max": 12}, "seizure": {"score": 4, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 0, "max": 12}}'::jsonb, agreement_bonus = 0 WHERE listing_id = 'd0000000-0000-0000-0000-000000000151';

UPDATE listings SET title_translated = '1969 Volkswagen Beetle, body lifted.' WHERE id = 'd0000000-0000-0000-0000-000000000155';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": false, "predicted_product": null, "predicted_species": null, "confidence": 0.0, "visual_evidence": "Image analysis failed", "alternative_explanations": null}, "per_image_results": [], "image_risk_score": 0.0}'::jsonb, image_risk_score = 0.0, text_image_agreement = 'disagree', risk_score = 57, alert_tier = 'yellow', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 7, "max": 12}, "seizure": {"score": 4, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 0, "max": 12}}'::jsonb, agreement_bonus = 0 WHERE listing_id = 'd0000000-0000-0000-0000-000000000155';

UPDATE listings SET title_translated = 'Turtle shell, antique, 17.5*15 inches' WHERE id = 'd0000000-0000-0000-0000-000000000156';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": false, "predicted_product": null, "predicted_species": null, "confidence": 0.0, "visual_evidence": "Image analysis failed", "alternative_explanations": null}, "per_image_results": [], "image_risk_score": 0.0}'::jsonb, image_risk_score = 0.0, text_image_agreement = 'disagree', risk_score = 57, alert_tier = 'yellow', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 7, "max": 12}, "seizure": {"score": 4, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 0, "max": 12}}'::jsonb, agreement_bonus = 0 WHERE listing_id = 'd0000000-0000-0000-0000-000000000156';

UPDATE listings SET title_translated = 'Tortoiseshell-colored resin hair clip with gold pattern 250 baht' WHERE id = 'd0000000-0000-0000-0000-000000000157';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": false, "predicted_product": null, "predicted_species": null, "confidence": 0.0, "visual_evidence": "Image analysis failed", "alternative_explanations": null}, "per_image_results": [], "image_risk_score": 0.0}'::jsonb, image_risk_score = 0.0, text_image_agreement = 'disagree', risk_score = 57, alert_tier = 'yellow', signal_breakdown = '{"code_word": {"score": 15, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 7, "max": 12}, "seizure": {"score": 4, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 0, "max": 12}}'::jsonb, agreement_bonus = 0 WHERE listing_id = 'd0000000-0000-0000-0000-000000000157';

UPDATE listings SET title_translated = 'Phra Sothon 18k stamped under the ring, is a Buddha image that has been a part of the nation for a long time. Whoever goes to ask for blessings will experience success and fulfillment in every way.' WHERE id = 'd0000000-0000-0000-0000-000000000044';
UPDATE listing_analysis SET image_classification = '{"primary_classification": {"product_detected": false, "predicted_product": null, "confidence": 0.0, "visual_evidence": "The image shows a ring with a red emblem and decorative stones.", "alternative_explanations": "The ring appears to be made of metal and synthetic or non-CITES-listed materials.", "predicted_species": null}, "per_image_results": [{"product_detected": false, "predicted_product": null, "confidence": 0.0, "visual_evidence": "The image shows a ring with a red emblem and decorative stones.", "alternative_explanations": "The ring appears to be made of metal and synthetic or non-CITES-listed materials.", "predicted_species": null}], "image_risk_score": 0.0}'::jsonb, image_risk_score = 0.0, text_image_agreement = 'disagree', risk_score = 60, alert_tier = 'amber', signal_breakdown = '{"code_word": {"score": 11, "max": 15}, "cites": {"score": 25, "max": 25}, "iucn": {"score": 10, "max": 12}, "seizure": {"score": 8, "max": 13}, "geographic": {"score": 6, "max": 10}, "seller": {"score": 0, "max": 10}, "price": {"score": 0, "max": 3}, "image": {"score": 0, "max": 12}}'::jsonb, agreement_bonus = 0 WHERE listing_id = 'd0000000-0000-0000-0000-000000000044';

-- Intelligence briefs generated by Claude Sonnet
DELETE FROM intelligence_briefs;

INSERT INTO intelligence_briefs (listing_id, brief_type, executive_summary, full_brief, recommended_actions, jurisdictions, generated_by) VALUES ('d0000000-0000-0000-0000-000000000102', 'auto', 'Detection scored 81/100 (red) on facebook.com.', '{"executive_summary": "Detection scored 81/100 (red) on facebook.com.", "risk_assessment": "Automated brief \u2014 LLM unavailable.", "key_evidence": [], "species_profile": "", "legal_framework": [], "recommended_actions": ["Manual review recommended"], "confidence_statement": "Automated assessment only", "alternative_explanations": []}'::jsonb, ARRAY['Manual review recommended'], '{}'::text[], 'claude-sonnet');
INSERT INTO intelligence_briefs (listing_id, brief_type, executive_summary, full_brief, recommended_actions, jurisdictions, generated_by) VALUES ('d0000000-0000-0000-0000-000000000101', 'auto', 'Detection scored 81/100 (red) on facebook.com.', '{"executive_summary": "Detection scored 81/100 (red) on facebook.com.", "risk_assessment": "Automated brief \u2014 LLM unavailable.", "key_evidence": [], "species_profile": "", "legal_framework": [], "recommended_actions": ["Manual review recommended"], "confidence_statement": "Automated assessment only", "alternative_explanations": []}'::jsonb, ARRAY['Manual review recommended'], '{}'::text[], 'claude-sonnet');
INSERT INTO intelligence_briefs (listing_id, brief_type, executive_summary, full_brief, recommended_actions, jurisdictions, generated_by) VALUES ('d0000000-0000-0000-0000-000000000108', 'auto', 'Detection scored 81/100 (red) on facebook.com.', '{"executive_summary": "Detection scored 81/100 (red) on facebook.com.", "risk_assessment": "Automated brief \u2014 LLM unavailable.", "key_evidence": [], "species_profile": "", "legal_framework": [], "recommended_actions": ["Manual review recommended"], "confidence_statement": "Automated assessment only", "alternative_explanations": []}'::jsonb, ARRAY['Manual review recommended'], '{}'::text[], 'claude-sonnet');
INSERT INTO intelligence_briefs (listing_id, brief_type, executive_summary, full_brief, recommended_actions, jurisdictions, generated_by) VALUES ('d0000000-0000-0000-0000-000000000110', 'auto', 'Detection scored 81/100 (red) on facebook.com.', '{"executive_summary": "Detection scored 81/100 (red) on facebook.com.", "risk_assessment": "Automated brief \u2014 LLM unavailable.", "key_evidence": [], "species_profile": "", "legal_framework": [], "recommended_actions": ["Manual review recommended"], "confidence_statement": "Automated assessment only", "alternative_explanations": []}'::jsonb, ARRAY['Manual review recommended'], '{}'::text[], 'claude-sonnet');
INSERT INTO intelligence_briefs (listing_id, brief_type, executive_summary, full_brief, recommended_actions, jurisdictions, generated_by) VALUES ('d0000000-0000-0000-0000-000000000111', 'auto', 'Detection scored 81/100 (red) on facebook.com.', '{"executive_summary": "Detection scored 81/100 (red) on facebook.com.", "risk_assessment": "Automated brief \u2014 LLM unavailable.", "key_evidence": [], "species_profile": "", "legal_framework": [], "recommended_actions": ["Manual review recommended"], "confidence_statement": "Automated assessment only", "alternative_explanations": []}'::jsonb, ARRAY['Manual review recommended'], '{}'::text[], 'claude-sonnet');
INSERT INTO intelligence_briefs (listing_id, brief_type, executive_summary, full_brief, recommended_actions, jurisdictions, generated_by) VALUES ('d0000000-0000-0000-0000-000000000103', 'auto', 'Detection scored 81/100 (red) on facebook.com.', '{"executive_summary": "Detection scored 81/100 (red) on facebook.com.", "risk_assessment": "Automated brief \u2014 LLM unavailable.", "key_evidence": [], "species_profile": "", "legal_framework": [], "recommended_actions": ["Manual review recommended"], "confidence_statement": "Automated assessment only", "alternative_explanations": []}'::jsonb, ARRAY['Manual review recommended'], '{}'::text[], 'claude-sonnet');
INSERT INTO intelligence_briefs (listing_id, brief_type, executive_summary, full_brief, recommended_actions, jurisdictions, generated_by) VALUES ('d0000000-0000-0000-0000-000000000104', 'auto', 'Detection scored 81/100 (red) on facebook.com.', '{"executive_summary": "Detection scored 81/100 (red) on facebook.com.", "risk_assessment": "Automated brief \u2014 LLM unavailable.", "key_evidence": [], "species_profile": "", "legal_framework": [], "recommended_actions": ["Manual review recommended"], "confidence_statement": "Automated assessment only", "alternative_explanations": []}'::jsonb, ARRAY['Manual review recommended'], '{}'::text[], 'claude-sonnet');
INSERT INTO intelligence_briefs (listing_id, brief_type, executive_summary, full_brief, recommended_actions, jurisdictions, generated_by) VALUES ('d0000000-0000-0000-0000-000000000105', 'auto', 'Detection scored 81/100 (red) on facebook.com.', '{"executive_summary": "Detection scored 81/100 (red) on facebook.com.", "risk_assessment": "Automated brief \u2014 LLM unavailable.", "key_evidence": [], "species_profile": "", "legal_framework": [], "recommended_actions": ["Manual review recommended"], "confidence_statement": "Automated assessment only", "alternative_explanations": []}'::jsonb, ARRAY['Manual review recommended'], '{}'::text[], 'claude-sonnet');
INSERT INTO intelligence_briefs (listing_id, brief_type, executive_summary, full_brief, recommended_actions, jurisdictions, generated_by) VALUES ('d0000000-0000-0000-0000-000000000107', 'auto', 'Detection scored 81/100 (red) on facebook.com.', '{"executive_summary": "Detection scored 81/100 (red) on facebook.com.", "risk_assessment": "Automated brief \u2014 LLM unavailable.", "key_evidence": [], "species_profile": "", "legal_framework": [], "recommended_actions": ["Manual review recommended"], "confidence_statement": "Automated assessment only", "alternative_explanations": []}'::jsonb, ARRAY['Manual review recommended'], '{}'::text[], 'claude-sonnet');
INSERT INTO intelligence_briefs (listing_id, brief_type, executive_summary, full_brief, recommended_actions, jurisdictions, generated_by) VALUES ('d0000000-0000-0000-0000-000000000097', 'auto', 'Detection scored 81/100 (red) on facebook.com.', '{"executive_summary": "Detection scored 81/100 (red) on facebook.com.", "risk_assessment": "Automated brief \u2014 LLM unavailable.", "key_evidence": [], "species_profile": "", "legal_framework": [], "recommended_actions": ["Manual review recommended"], "confidence_statement": "Automated assessment only", "alternative_explanations": []}'::jsonb, ARRAY['Manual review recommended'], '{}'::text[], 'claude-sonnet');
INSERT INTO intelligence_briefs (listing_id, brief_type, executive_summary, full_brief, recommended_actions, jurisdictions, generated_by) VALUES ('d0000000-0000-0000-0000-000000000099', 'auto', 'Detection scored 81/100 (red) on facebook.com.', '{"executive_summary": "Detection scored 81/100 (red) on facebook.com.", "risk_assessment": "Automated brief \u2014 LLM unavailable.", "key_evidence": [], "species_profile": "", "legal_framework": [], "recommended_actions": ["Manual review recommended"], "confidence_statement": "Automated assessment only", "alternative_explanations": []}'::jsonb, ARRAY['Manual review recommended'], '{}'::text[], 'claude-sonnet');
INSERT INTO intelligence_briefs (listing_id, brief_type, executive_summary, full_brief, recommended_actions, jurisdictions, generated_by) VALUES ('d0000000-0000-0000-0000-000000000096', 'auto', 'Detection scored 81/100 (red) on facebook.com.', '{"executive_summary": "Detection scored 81/100 (red) on facebook.com.", "risk_assessment": "Automated brief \u2014 LLM unavailable.", "key_evidence": [], "species_profile": "", "legal_framework": [], "recommended_actions": ["Manual review recommended"], "confidence_statement": "Automated assessment only", "alternative_explanations": []}'::jsonb, ARRAY['Manual review recommended'], '{}'::text[], 'claude-sonnet');
INSERT INTO intelligence_briefs (listing_id, brief_type, executive_summary, full_brief, recommended_actions, jurisdictions, generated_by) VALUES ('d0000000-0000-0000-0000-000000000109', 'auto', 'Detection scored 64/100 (amber) on facebook.com.', '{"executive_summary": "Detection scored 64/100 (amber) on facebook.com.", "risk_assessment": "Automated brief \u2014 LLM unavailable.", "key_evidence": [], "species_profile": "", "legal_framework": [], "recommended_actions": ["Manual review recommended"], "confidence_statement": "Automated assessment only", "alternative_explanations": []}'::jsonb, ARRAY['Manual review recommended'], '{}'::text[], 'claude-sonnet');
INSERT INTO intelligence_briefs (listing_id, brief_type, executive_summary, full_brief, recommended_actions, jurisdictions, generated_by) VALUES ('d0000000-0000-0000-0000-000000000098', 'auto', 'Detection scored 64/100 (amber) on facebook.com.', '{"executive_summary": "Detection scored 64/100 (amber) on facebook.com.", "risk_assessment": "Automated brief \u2014 LLM unavailable.", "key_evidence": [], "species_profile": "", "legal_framework": [], "recommended_actions": ["Manual review recommended"], "confidence_statement": "Automated assessment only", "alternative_explanations": []}'::jsonb, ARRAY['Manual review recommended'], '{}'::text[], 'claude-sonnet');
INSERT INTO intelligence_briefs (listing_id, brief_type, executive_summary, full_brief, recommended_actions, jurisdictions, generated_by) VALUES ('d0000000-0000-0000-0000-000000000100', 'auto', 'Detection scored 64/100 (amber) on facebook.com.', '{"executive_summary": "Detection scored 64/100 (amber) on facebook.com.", "risk_assessment": "Automated brief \u2014 LLM unavailable.", "key_evidence": [], "species_profile": "", "legal_framework": [], "recommended_actions": ["Manual review recommended"], "confidence_statement": "Automated assessment only", "alternative_explanations": []}'::jsonb, ARRAY['Manual review recommended'], '{}'::text[], 'claude-sonnet');
INSERT INTO intelligence_briefs (listing_id, brief_type, executive_summary, full_brief, recommended_actions, jurisdictions, generated_by) VALUES ('d0000000-0000-0000-0000-000000000117', 'auto', 'Detection scored 64/100 (amber) on facebook.com.', '{"executive_summary": "Detection scored 64/100 (amber) on facebook.com.", "risk_assessment": "Automated brief \u2014 LLM unavailable.", "key_evidence": [], "species_profile": "", "legal_framework": [], "recommended_actions": ["Manual review recommended"], "confidence_statement": "Automated assessment only", "alternative_explanations": []}'::jsonb, ARRAY['Manual review recommended'], '{}'::text[], 'claude-sonnet');
INSERT INTO intelligence_briefs (listing_id, brief_type, executive_summary, full_brief, recommended_actions, jurisdictions, generated_by) VALUES ('d0000000-0000-0000-0000-000000000138', 'auto', 'Detection scored 64/100 (amber) on facebook.com.', '{"executive_summary": "Detection scored 64/100 (amber) on facebook.com.", "risk_assessment": "Automated brief \u2014 LLM unavailable.", "key_evidence": [], "species_profile": "", "legal_framework": [], "recommended_actions": ["Manual review recommended"], "confidence_statement": "Automated assessment only", "alternative_explanations": []}'::jsonb, ARRAY['Manual review recommended'], '{}'::text[], 'claude-sonnet');
INSERT INTO intelligence_briefs (listing_id, brief_type, executive_summary, full_brief, recommended_actions, jurisdictions, generated_by) VALUES ('d0000000-0000-0000-0000-000000000044', 'auto', 'Detection scored 60/100 (amber) on kaidee.com.', '{"executive_summary": "Detection scored 60/100 (amber) on kaidee.com.", "risk_assessment": "Automated brief \u2014 LLM unavailable.", "key_evidence": [], "species_profile": "", "legal_framework": [], "recommended_actions": ["Manual review recommended"], "confidence_statement": "Automated assessment only", "alternative_explanations": []}'::jsonb, ARRAY['Manual review recommended'], '{}'::text[], 'claude-sonnet');
